project:
  type: website

website:
  title: "Analysis results"
  navbar:
    right:
      - href: https://github.com/WellcomeIdeathon2023/LSHTMCrick_team
        text: Github repository
        icon: github
  sidebar:
    contents: []

  
number-sections: true
    
format:
  html:
    theme: cosmo
    toc: true
